### ISSUE TITLE
neovim supporting

### ISSUE THREAD

**Issue by ayoubelmhamdi** [frozolotl/tree-sitter-typst#2]
### Try to useit in neovim but not work

```lua
    local parser_config = require('nvim-treesitter.parsers').get_parser_configs()
    parser_config.typst = {
      install_info = {
        url = '/data/github/tree-sitter-typst',
        files = { 'src/parser.c' },
        branch = 'main',
      },
      filetype = 'typst', -- if filetype does not agrees with parser name
    }
```
### it is should be in the path like:
```lua
queries/{language}/{locals,highlights,textobjects}.scm
```

```shell
ln -s /data/github/tree-sitter-typst/queries/highlights.scm \
    ~/.config/nvim/after/plugin
```

```log
Error executing lua callback: Failed to load parser for language 'typst': uv_dlopen: /home/mhamdi/.local/share/nvim/lazy/nv
im-treesitter/parser/typst.so: undefined symbol: tree_sitter_typst_external_scanner_create
stack traceback:
        [C]: in function '_ts_add_language'
        /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:99: in function 'add'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:85: in function 'new'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:61: in function '_create_parser'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:469: in function 'start'
        ...m/lazy/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...vim/lazy/nvim-treesitter/lua/nvim-
treesitter/configs.lua:132>
```

**Comment by Slickytail** [comment]
You need to include the scanner file:
` files = { 'src/parser.c' , 'src/scanner.cc'},`

**Comment by ayoubelmhamdi** [comment]
the error is gone, but there no highlighting

<img src="https://user-images.githubusercontent.com/34358145/233978236-83fabfcb-7475-41a3-b390-a70c553f276a.png"  width="60%" height="30%">

**Comment by slashformotion** [comment]
works on helix, try with the latest commit

**Comment by ayoubelmhamdi** [comment]
yah it work, the problem is come from my colorscheme that not detected it, because it is detected by Playground plugins, i will try to override my theme or using some tree-sitter query to make the typst query understand by Any theme.

**Comment by frozolotl** [comment]
I previously did not close it because it showed not yet correct parsing of code.

Now I'm closing this issue because I think that would be better served by a separate issue if necessary.

**Comment by peng1999** [comment]
> i will try to override my theme or using some tree-sitter query to make the typst query understand by Any theme.

@ayoubelmhamdi Did you make the query that understands by nvim theme? Could you please open source the query file somewhere?

**Comment by TheZoq2** [comment]
Now that nvim-treesitter more closely aligns with the helix highlight groups https://github.com/nvim-treesitter/nvim-treesitter/commit/1ae9b0e4558fe7868f8cda2db65239cfb14836d0, this works almost out of the box with neovim

However, as pointed out in the initial message in this issue, neovim assumes queries to be in `queries/typst/{highlight,indent}.scm` rather than just `queries/{highlights,indent}.scm`

Since the helix workflow in the readme relies on symlinking these things anyway, would you be open to moving the files to make use with nvim easier. In my fork where I made this move, the installation is as easy as
```viml
Plug 'https://github.com/TheZoq2/tree-sitter-typst'
```
```lua
require'nvim-treesitter.install'.prefer_git = true
parser_config.typst = {
  install_info = {
    url = "https://github.com/frozolotl/tree-sitter-typst.git", -- local path or git repo
    files = {"src/parser.c", "src/scanner.cc"},
  },
  filetype = "typst", -- if filetype does not match the parser name
}
```

**Comment by frozolotl** [comment]
> Since the helix workflow in the readme relies on symlinking these things anyway, would you be open to moving the files to make use with nvim easier. In my fork where I made this move, the installation is as easy as

That sounds like a great idea! Since you already did the work, would you be willig to create a pull request?
